### ISSUE TITLE
Avoid using chrome.runtime.sendMessage() wherever possible

### ISSUE THREAD

**Issue by gorhill** [gorhill/httpswitchboard#345]
The status of the issue:

https://code.google.com/p/chromium/issues/detail?id=320723

is ambiguous. It's not marked as ~~fixed~~ "verified", on the other hand it's labeled M32. Quite unclear whether the memory leak was solved or not.

In any case, there are many places in HTTPSB where using a long-lived connection makes more sense than using a one time message, which comes with a good overhead if I read correctly.

**Comment by picwellwisher12pk** [comment]
@gorhill can you help me in same context.
