### ISSUE TITLE
xmlhttprequest = xhr

### ISSUE THREAD

**Issue by ghost** [gorhill/httpswitchboard#412]
Hi. Please consider using the same name (either `xmlhttprequest` or `XHR` ) in these cases:

![xhr1of2](https://cloud.githubusercontent.com/assets/5661825/4266243/87ec5f14-3c78-11e4-8a85-dcdf8019d10d.png)
![xhr2of2](https://cloud.githubusercontent.com/assets/5661825/4266244/8c3c5862-3c78-11e4-960a-13baeb3d2493.png)
## the actual reason is because I had no idea why this wouldn't work:

![xhr3of2](https://cloud.githubusercontent.com/assets/5661825/4266241/82d121d6-3c78-11e4-88a9-d649d15c6255.png)

Thank you:)

**Comment by Andyyun1982** [comment]
#
