### ISSUE TITLE
Causing crash at Chrome start-up with proxy settings

### ISSUE THREAD

**Issue by Buddle** [gorhill/httpswitchboard#427]
**Browser:Chrome x64 39.0.2171.99 Stable on Windows
[igrigorik/node-spdyproxy](https://github.com/igrigorik/node-spdyproxy) is running on my server.**

### `Two way SSL authentication` is turn on and all settings on both server and client,my conputer seem correct.

* It doesn't matter Chrome is set with arguement `--proxy-server' or with [SwithcSharp](https://chrome.google.com/webstore/detail/dpplabbmogkhghncfbfdeeokoefdjegm),Chrome crashes as been expected.
* If proxy settings is on,Chrome crashes with a prompt windows from system asking me whether to let Chrome restart as soon as it is started and it doesn't generate any report which could be found in`chrome://crashes`.
* If proxy settings is on,but there is any issue that causes failure of client authentication,Chrome doesn't crash.For example,it is able to start when server cert or client cert is untrusted.
* If proxy settings is on,and an issue is made that I disable the cleint cert, as mentioned above and I enable the client cert after Chrome starts without crashes as expected,Chrome is still able to work well beyond my expectation.It can access the Internet via proxy with authentication of client certificate.
* If proxy settings is on and HTTPswithcboard is disabled,Chrome is able to work as usual and access the Internet through proxy after starting up with no crash.

### `Two way SSL authentication` is turn off and authentication is based on `Basic-Auth`.
No matter HTTPswithcboard is disabled or not,all works fine without issue,no crash.

**Is it compatible with SSL client auth?**

**Comment by gorhill** [comment]
Two things:

1. HTTP Switchboard is no longer maintained, it is superseded by uMatrix.
2. HTTP Switchboard is javascript: javascript doesn't crash. When a browser crashes, it means there is a bug in the browser, and this needs to be reported to the browser devs.

**Comment by Buddle** [comment]
Thank you.I will turn to uMatrix
