### ISSUE TITLE
keybindings?

### ISSUE THREAD

**Issue by anarcat** [gorhill/httpswitchboard#428]
are there way to operate httpswitchboard only from the keyboard?

**Comment by gorhill** [comment]
All the available key bindings appear in the _"Keyboard shortcuts"_ dialog of the _Extensions_ page.

**Comment by anarcat** [comment]
oooh, never saw that button before, thanks!

in case people find this at the bottom right of the `chrome://extensions/` URL, there's a `Keyboard shortcuts` link.
