### ISSUE TITLE
HTTP switchboard is not showing up in the Google store

### ISSUE THREAD

**Issue by Eureka-sevenfold** [gorhill/httpswitchboard#430]
it says this 
An error occurred:

Item not found. This item may have been removed by its author.
Take me back to the store

**Comment by gorhill** [comment]
Chrome took it down. I am guessing the icon resembles too much the icon of uMatrix. I am not too motivated to address this, as uMatrix supersedes HTTPSB since it came out, I haven't touched HTTPSB's code in ages now.

**Comment by Eureka-sevenfold** [comment]
thanks for the I am right now used the µMatrix is there any difference from this an HTTP switchboard

**Comment by my-password-is-password** [comment]
https://github.com/gorhill/uMatrix/wiki/Changes-from-HTTP-Switchboard
