### ISSUE TITLE
GUI disorganized on this page

### ISSUE THREAD

**Issue by attila-lendvai** [gorhill/httpswitchboard#433]
when i look at this page:

https://www.slideshare.net/signup

the httpsb GUI is disorganized. maybe some CSS rules leak into it?

HTTP Switchboard 1.0.1.5
Chromium Version 49.0.2623.87 Built on 8.3, running on Debian 8.3 (64-bit)

**Comment by Atavic** [comment]
Try the newer addons: µMatrix & µBlock.

**Comment by attila-lendvai** [comment]
that works, thanks! didn't know there was a brand change...
